apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  namespace: codelabs
spec:
  template:
    metadata:
      labels:
        daytona-binding: init
    spec:
      serviceAccountName: paas-codelab
      containers:
      - image: gcr.io/cloudrun/hello
