/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/dgerd/daytona-binding/pkg/apis/daytonabinding/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDaytonaBindings implements DaytonaBindingInterface
type FakeDaytonaBindings struct {
	Fake *FakeBindingV1alpha1
	ns   string
}

var daytonabindingsResource = schema.GroupVersionResource{Group: "binding.app", Version: "v1alpha1", Resource: "daytonabindings"}

var daytonabindingsKind = schema.GroupVersionKind{Group: "binding.app", Version: "v1alpha1", Kind: "DaytonaBinding"}

// Get takes name of the daytonaBinding, and returns the corresponding daytonaBinding object, and an error if there is any.
func (c *FakeDaytonaBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.DaytonaBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(daytonabindingsResource, c.ns, name), &v1alpha1.DaytonaBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaytonaBinding), err
}

// List takes label and field selectors, and returns the list of DaytonaBindings that match those selectors.
func (c *FakeDaytonaBindings) List(opts v1.ListOptions) (result *v1alpha1.DaytonaBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(daytonabindingsResource, daytonabindingsKind, c.ns, opts), &v1alpha1.DaytonaBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DaytonaBindingList{ListMeta: obj.(*v1alpha1.DaytonaBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.DaytonaBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested daytonaBindings.
func (c *FakeDaytonaBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(daytonabindingsResource, c.ns, opts))

}

// Create takes the representation of a daytonaBinding and creates it.  Returns the server's representation of the daytonaBinding, and an error, if there is any.
func (c *FakeDaytonaBindings) Create(daytonaBinding *v1alpha1.DaytonaBinding) (result *v1alpha1.DaytonaBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(daytonabindingsResource, c.ns, daytonaBinding), &v1alpha1.DaytonaBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaytonaBinding), err
}

// Update takes the representation of a daytonaBinding and updates it. Returns the server's representation of the daytonaBinding, and an error, if there is any.
func (c *FakeDaytonaBindings) Update(daytonaBinding *v1alpha1.DaytonaBinding) (result *v1alpha1.DaytonaBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(daytonabindingsResource, c.ns, daytonaBinding), &v1alpha1.DaytonaBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaytonaBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDaytonaBindings) UpdateStatus(daytonaBinding *v1alpha1.DaytonaBinding) (*v1alpha1.DaytonaBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(daytonabindingsResource, "status", c.ns, daytonaBinding), &v1alpha1.DaytonaBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaytonaBinding), err
}

// Delete takes name of the daytonaBinding and deletes it. Returns an error if one occurs.
func (c *FakeDaytonaBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(daytonabindingsResource, c.ns, name), &v1alpha1.DaytonaBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDaytonaBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(daytonabindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DaytonaBindingList{})
	return err
}

// Patch applies the patch and returns the patched daytonaBinding.
func (c *FakeDaytonaBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DaytonaBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daytonabindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DaytonaBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DaytonaBinding), err
}
